Feature/ep consumable
OpenPerpetuum/OPDB-docs pull request #113
Opened 2018-12-29 20:43 UTC by Ketsuekiame

Add EP Boost items to the DB - Note that this patch will crash the syndicate shop if the server code is not updated due to the missing templates

2018-12-29 21:45 UTC, MikeJeffers requested changes
Patches to be reviewed go in ../Staging_Dev/
SQL in there (and not in a subfolder) is "staged" to later be bundled in a patch (which may be 1-N separate sql files/patches/projects)

2018-12-29 22:32 UTC, MikeJeffers submitted a review, later dismissed

2018-12-29 22:34 UTC, MikeJeffers commented
DO NOT MERGE
Until after Patch 8 on 12/30 - and @Bler reviews!

2018-12-29 23:17 UTC, MikeJeffers commented
Tested and working with https://github.com/OpenPerpetuum/PerpetuumServer/pull/89

Please note these PR's depend on eachother!

2019-01-21 18:47 UTC, MikeJeffers commented
Refactored to support : https://github.com/OpenPerpetuum/PerpetuumServer/pull/92
Tested locally ready for review

2019-01-21 19:01 UTC, nref-dan commented on Staging_Dev/AddEPItemPatch.sql
Duplicate the above  if statement here but for the opp.X procedure. This is to ensure there isn't a patch error trying to overwrite the procedure

2019-01-21 19:02 UTC, Ketsuekiame commented on Staging_Dev/AddEPItemPatch.sql
Same here

2019-01-26 21:03 UTC, Bler approved these changes
approved

2019-01-26 21:04 UTC, merged