Welcome chat message
OpenPerpetuum/OPDB-docs pull request #150
Opened 2019-05-09 03:09 UTC by clouths

Closes: [OpenPerpetuum/OP-Project#142](https://github.com/OpenPerpetuum/OP-Project/issues/142)
For: [OpenPerpetuum/PerpetuumServer#100](https://github.com/OpenPerpetuum/PerpetuumServer/pull/100)

The test procedure is located [here](https://github.com/OpenPerpetuum/PerpetuumServer/pull/100)

2019-05-11 18:09 UTC, MikeJeffers requested changes
Some content tweaks

2019-05-11 18:09 UTC, MikeJeffers commented on Staging_Dev/20190508T014400Z_welcome_chat_message.sql
> +VALUES (1, 'TutorialCompleteMessage', 'Attention Nia members, we have a new challenger to the world: $NAME$');
Let's workshop the message content.

2019-05-11 18:09 UTC, MikeJeffers commented on Staging_Dev/20190508T014400Z_welcome_chat_message.sql
> +			N'New Player Announcer', --nick
And might consider a new name (prepend "[OPP]" ?) Will discuss

2019-05-20 00:14 UTC, MikeJeffers approved these changes

2019-05-20 00:15 UTC, MikeJeffers commented
@Bler Still needs your signoff - merge when ready

2019-06-07 17:14 UTC, Bler approved these changes
Approved

2019-06-07 17:14 UTC, merged